### ISSUE TITLE
ImportError: attempted relative import with no known parent package 

### ISSUE THREAD

**Issue by zaper4life** [googlesamples/assistant-sdk-python#160]
Couldn't find anyway to make it work, couldn't find support online, I'm a newb who want to play with experts, if you can help me to get it to work I'll love it.

After running:

python -m pushtotalk --device-id 'my-device-identifier' 

I've encountered following error:

pushtotalk.py", line 38, in <module>
    from . import (
ImportError: attempted relative import with no known parent package

**Comment by Fleker** [comment]
Which python version are you using? Python 3?

**Comment by zaper4life** [comment]
I ran:
_brew install python python3_
it completed successfully :) 

Than I ran:
_python --version_
But got:
_Python 2.7.10_

I install python launcher from a downloaded dmg and it version appear to be:
_3.6.4_

**Comment by Fleker** [comment]
Do you have access to `python3` in the terminal? Can you run `python3 --version`? What if you run `python3 -m pushtotalk --device-id 'my-device-identifier'`?

**Comment by zaper4life** [comment]
Nope, not it, I'll attach my actions.
[MaybeIjustSuckAtSruff.txt](https://github.com/googlesamples/assistant-sdk-python/files/1622613/MaybeIjustSuckAtSruff.txt)

**Comment by Fleker** [comment]
@proppy do you know more about this bug? It appears to be something to do with [the Python imports here](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L38).

I've pasted the previous logs below for easier access
```
(env) kscdtl01rr2575:grpc oassraf$ python -m devicetool register --model 'Omer_Link.932' \
>                               --type LIGHT --trait action.devices.traits.OnOff \
>                               --manufacturer 'Assistant SDK developer' \
>                               --product-name 'Assistant SDK light' \
>                               --description 'Assistant SDK light device' \
>                               --device 'Omer_Link.932' \
>                               --nickname 'My Assistant Light'
Usage: devicetool.py register [OPTIONS]

Error: Missing option "--client-type".  Choose from SERVICE, LIBRARY.
(env) kscdtl01rr2575:grpc oassraf$ python -m devicetool register --model 'Omer_Link.932'                               --type LIGHT --trait action.devices.traits.OnOff                               --manufacturer 'Assistant SDK developer'                               --product-name 'Assistant SDK light'                               --description 'Assistant SDK light device'                               --device 'Omer_Link.932'                               --nickname 'My Assistant Light' --client-type SERVICE
Updating existing device model: Omer_Link.932
Model Omer_Link.932 successfully registered
Updating existing device: Omer_Link.932
Device instance Omer_Link.932 successfully registered
(env) kscdtl01rr2575:grpc oassraf$ python3 -m pushtotalk --device-id 'Omer_Link.932'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/oassraf/Downloads/assistant-sdk-python-master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py", line 38, in <module>
    from . import (
ImportError: attempted relative import with no known parent package
```

**Comment by proppy** [comment]
This seems like an issue with python 3.6

**Comment by proppy** [comment]
I can reproduce the issue when trying to run with python3.6 -m pushtotalk
```
(env) grpc 👺  python3.6 -m pushtotalk
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/google/home/proppy/src/devrel/samples/assistant/embedded-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py", line 38, in <module>
    from . import (
ImportError: attempted relative import with no known parent package
```

The other documented way to run the package work as expected:
https://developers.google.com/assistant/sdk/guides/service/python/embed/run-sample
```
(env) grpc 👺  googlesamples-assistant-pushtotalk
INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
```

This also work:
```
(env) grpc 👺  python3.6 -m googlesamples.assistant.grpc.pushtotalk
INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
```

We still have an issue when running the sample directly from the file.
```
(env) grpc 🍡  python pushtotalk.py
Traceback (most recent call last):
  File "pushtotalk.py", line 38, in <module>
    from . import (
ImportError: cannot import name 'assistant_helpers'
```

I think this is related to this 3.6 changes:
https://bugs.python.org/issue18018

So we need to also catch `ImportError`.

We could also re-check if the boilerplate (introduced in https://github.com/googlesamples/assistant-sdk-python/commit/22db0715767fc85cc20ba40982807cbd300712fb) is indeed necessary by testing the different way to run the sample with all python versions.
